# Change these first
owner: Osdop # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sitio Web
    url: https://www.osdop.org.ar
    method: POST
  - name: Servicios
    url: https://servicios.osdop.org.ar
    method: GET
    expectedStatusCodes:
      - 401
  - name: Vpn
    url: https://vpn.osdop.org.ar
    method: GET
  - name: Autogestion
    url: https://autogestion.osdop.org.ar
    method: GET
  - name: Correo Electronico
    check: "tcp-ping"
    url: mail.osdop.org.ar
    port: 110

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.osdop.org.ar
  # baseUrl: /upptime
  logoUrl: https://www.osdop.org.ar/wp-content/uploads/2021/08/favicon-io.png
  name: Osdop TI Status
  introTitle: "**OSDOP TI Status** es un sitio para monitoreo de servicios informaticos de la organizacion."
  introMessage: Se veran reflejados los estados de algunos de los servicios informaticos publicados. - Powered by GitHub and Upptime
  navbar:
    - title: Osdop TI Status
      href: /
    - title: Sitio Web Osdop
      href: https://www.osdop.org.ar

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
